function [sig_all, sizes] = signature_extractor(num_cluster,fc,ovp,fc_sig,ovp_sig,peptides_union,fc_all,idx_Cs)

if num_cluster==2
    sig_C1=peptides_union(fc_sig(:,1)>fc & ovp_sig(:,1)<ovp & nanmedian(fc_all(:,idx_Cs{1,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{1,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2));
    sig_C2=peptides_union(fc_sig(:,2)>fc & ovp_sig(:,2)<ovp & nanmedian(fc_all(:,idx_Cs{2,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{2,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2));
    sig_all=[[sig_C1,repmat({'C1'},length(sig_C1),1)];[sig_C2,repmat({'C2'},length(sig_C2),1)]];
    sizes=[size(sig_C1,1),size(sig_C2,1)];
elseif num_cluster==3
    sig_C1=peptides_union(fc_sig(:,1)>fc & ovp_sig(:,1)<ovp & nanmedian(fc_all(:,idx_Cs{1,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{1,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2) & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{3,1}),2));
    sig_C2=peptides_union(fc_sig(:,2)>fc & ovp_sig(:,2)<ovp & nanmedian(fc_all(:,idx_Cs{2,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{2,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2) & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{3,1}),2));
    sig_C3=peptides_union(fc_sig(:,3)>fc & ovp_sig(:,3)<ovp & nanmedian(fc_all(:,idx_Cs{3,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{3,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{3,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2) & nanmedian(fc_all(:,idx_Cs{3,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2));
    sig_all=[[sig_C1,repmat({'C1'},length(sig_C1),1)];[sig_C2,repmat({'C2'},length(sig_C2),1)];[sig_C3,repmat({'C3'},length(sig_C3),1)]];
    sizes=[size(sig_C1,1),size(sig_C2,1),size(sig_C3,1)];
elseif num_cluster==4
    sig_C1=peptides_union(fc_sig(:,1)>fc & ovp_sig(:,1)<ovp & nanmedian(fc_all(:,idx_Cs{1,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{1,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2) & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{3,1}),2) & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{4,1}),2));
    sig_C2=peptides_union(fc_sig(:,2)>fc & ovp_sig(:,2)<ovp & nanmedian(fc_all(:,idx_Cs{2,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{2,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2) & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{3,1}),2) & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{4,1}),2));
    sig_C3=peptides_union(fc_sig(:,3)>fc & ovp_sig(:,3)<ovp & nanmedian(fc_all(:,idx_Cs{3,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{3,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{3,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2) & nanmedian(fc_all(:,idx_Cs{3,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2) & nanmedian(fc_all(:,idx_Cs{3,1}),2)>nanmedian(fc_all(:,idx_Cs{4,1}),2));
    sig_C4=peptides_union(fc_sig(:,4)>fc & ovp_sig(:,4)<ovp & nanmedian(fc_all(:,idx_Cs{4,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{4,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{4,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2) & nanmedian(fc_all(:,idx_Cs{4,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2) & nanmedian(fc_all(:,idx_Cs{4,1}),2)>nanmedian(fc_all(:,idx_Cs{3,1}),2));
    sig_all=[[sig_C1,repmat({'C1'},length(sig_C1),1)];[sig_C2,repmat({'C2'},length(sig_C2),1)];[sig_C3,repmat({'C3'},length(sig_C3),1)];[sig_C4,repmat({'C4'},length(sig_C4),1)]];
    sizes=[size(sig_C1,1),size(sig_C2,1),size(sig_C3,1),size(sig_C4,1)];
elseif num_cluster==5
    sig_C1=peptides_union(fc_sig(:,1)>fc & ovp_sig(:,1)<ovp & nanmedian(fc_all(:,idx_Cs{1,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{1,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2) & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{3,1}),2) & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{4,1}),2) & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{5,1}),2));
    sig_C2=peptides_union(fc_sig(:,2)>fc & ovp_sig(:,2)<ovp & nanmedian(fc_all(:,idx_Cs{2,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{2,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2) & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{3,1}),2) & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{4,1}),2) & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{5,1}),2));
    sig_C3=peptides_union(fc_sig(:,3)>fc & ovp_sig(:,3)<ovp & nanmedian(fc_all(:,idx_Cs{3,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{3,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{3,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2) & nanmedian(fc_all(:,idx_Cs{3,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2) & nanmedian(fc_all(:,idx_Cs{3,1}),2)>nanmedian(fc_all(:,idx_Cs{4,1}),2) & nanmedian(fc_all(:,idx_Cs{3,1}),2)>nanmedian(fc_all(:,idx_Cs{5,1}),2));
    sig_C4=peptides_union(fc_sig(:,4)>fc & ovp_sig(:,4)<ovp & nanmedian(fc_all(:,idx_Cs{4,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{4,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{4,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2) & nanmedian(fc_all(:,idx_Cs{4,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2) & nanmedian(fc_all(:,idx_Cs{4,1}),2)>nanmedian(fc_all(:,idx_Cs{3,1}),2) & nanmedian(fc_all(:,idx_Cs{4,1}),2)>nanmedian(fc_all(:,idx_Cs{5,1}),2));
    sig_C5=peptides_union(fc_sig(:,5)>fc & ovp_sig(:,5)<ovp & nanmedian(fc_all(:,idx_Cs{5,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{5,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{5,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2) & nanmedian(fc_all(:,idx_Cs{5,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2) & nanmedian(fc_all(:,idx_Cs{5,1}),2)>nanmedian(fc_all(:,idx_Cs{3,1}),2) & nanmedian(fc_all(:,idx_Cs{5,1}),2)>nanmedian(fc_all(:,idx_Cs{4,1}),2));
    sig_all=[[sig_C1,repmat({'C1'},length(sig_C1),1)];[sig_C2,repmat({'C2'},length(sig_C2),1)];[sig_C3,repmat({'C3'},length(sig_C3),1)];[sig_C4,repmat({'C4'},length(sig_C4),1)];[sig_C5,repmat({'C5'},length(sig_C5),1)]];
    sizes=[size(sig_C1,1),size(sig_C2,1),size(sig_C3,1),size(sig_C4,1),size(sig_C5,1)];
elseif num_cluster==6
    sig_C1=peptides_union(fc_sig(:,1)>fc & ovp_sig(:,1)<ovp & nanmedian(fc_all(:,idx_Cs{1,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{1,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2) & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{3,1}),2) & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{4,1}),2) & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{5,1}),2) & nanmedian(fc_all(:,idx_Cs{1,1}),2)>nanmedian(fc_all(:,idx_Cs{6,1}),2));
    sig_C2=peptides_union(fc_sig(:,2)>fc & ovp_sig(:,2)<ovp & nanmedian(fc_all(:,idx_Cs{2,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{2,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2) & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{3,1}),2) & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{4,1}),2) & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{5,1}),2) & nanmedian(fc_all(:,idx_Cs{2,1}),2)>nanmedian(fc_all(:,idx_Cs{6,1}),2));
    sig_C3=peptides_union(fc_sig(:,3)>fc & ovp_sig(:,3)<ovp & nanmedian(fc_all(:,idx_Cs{3,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{3,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{3,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2) & nanmedian(fc_all(:,idx_Cs{3,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2) & nanmedian(fc_all(:,idx_Cs{3,1}),2)>nanmedian(fc_all(:,idx_Cs{4,1}),2) & nanmedian(fc_all(:,idx_Cs{3,1}),2)>nanmedian(fc_all(:,idx_Cs{5,1}),2) & nanmedian(fc_all(:,idx_Cs{3,1}),2)>nanmedian(fc_all(:,idx_Cs{6,1}),2));
    sig_C4=peptides_union(fc_sig(:,4)>fc & ovp_sig(:,4)<ovp & nanmedian(fc_all(:,idx_Cs{4,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{4,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{4,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2) & nanmedian(fc_all(:,idx_Cs{4,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2) & nanmedian(fc_all(:,idx_Cs{4,1}),2)>nanmedian(fc_all(:,idx_Cs{3,1}),2) & nanmedian(fc_all(:,idx_Cs{4,1}),2)>nanmedian(fc_all(:,idx_Cs{5,1}),2) & nanmedian(fc_all(:,idx_Cs{4,1}),2)>nanmedian(fc_all(:,idx_Cs{6,1}),2));
    sig_C5=peptides_union(fc_sig(:,5)>fc & ovp_sig(:,5)<ovp & nanmedian(fc_all(:,idx_Cs{5,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{5,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{5,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2) & nanmedian(fc_all(:,idx_Cs{5,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2) & nanmedian(fc_all(:,idx_Cs{5,1}),2)>nanmedian(fc_all(:,idx_Cs{3,1}),2) & nanmedian(fc_all(:,idx_Cs{5,1}),2)>nanmedian(fc_all(:,idx_Cs{4,1}),2) & nanmedian(fc_all(:,idx_Cs{5,1}),2)>nanmedian(fc_all(:,idx_Cs{6,1}),2));
    sig_C6=peptides_union(fc_sig(:,6)>fc & ovp_sig(:,6)<ovp & nanmedian(fc_all(:,idx_Cs{6,1}),2)>0 & nanmedian(fc_all(:,~idx_Cs{6,1}),2)<0 & nanmedian(fc_all(:,idx_Cs{6,1}),2)>nanmedian(fc_all(:,idx_Cs{1,1}),2) & nanmedian(fc_all(:,idx_Cs{6,1}),2)>nanmedian(fc_all(:,idx_Cs{2,1}),2) & nanmedian(fc_all(:,idx_Cs{6,1}),2)>nanmedian(fc_all(:,idx_Cs{3,1}),2) & nanmedian(fc_all(:,idx_Cs{6,1}),2)>nanmedian(fc_all(:,idx_Cs{4,1}),2) & nanmedian(fc_all(:,idx_Cs{6,1}),2)>nanmedian(fc_all(:,idx_Cs{5,1}),2));
    sig_all=[[sig_C1,repmat({'C1'},length(sig_C1),1)];[sig_C2,repmat({'C2'},length(sig_C2),1)];[sig_C3,repmat({'C3'},length(sig_C3),1)];[sig_C4,repmat({'C4'},length(sig_C4),1)];[sig_C5,repmat({'C5'},length(sig_C5),1)],[sig_C6,repmat({'C6'},length(sig_C6),1)]];
    sizes=[size(sig_C1,1),size(sig_C2,1),size(sig_C3,1),size(sig_C4,1),size(sig_C5,1),size(sig_C6,1)];
end


